### ISSUE TITLE
LEDs doesn't blink

### ISSUE THREAD

**Issue by Martoni** [pepijndevos/apicula#9]
I followed the tutorial given in main README for the board TEC0117.
```
$ export GOWINHOME=/chemin/de/linstallation/gowin/IDE/
$ export DEVICE="GW1NR-9" # TEC0117
$ python dat19_h4x.py # makes $DEVICE.json
$ python tiled_fuzzer.py # makes $DEVICE.pickle
$ cd generic
$ bash simple.sh blinky.v # TEC0117
$ cd ..
$ python gowin_pack.py generic/pnrblinky.json
$ python gowin_unpack.py pack.fs
$ yosys -p "read_verilog -lib +/gowin/cells_sim.v; clean -purge; show" unpack.v
$ openFPGALoader -m -b littleBee pack.fs # FOSS programmer
```

 The bitstream pack.fs has been generated and downloaded with openFPGALoader but LEDs doesn't blink. All LED are on.

I used official «pinout» from Gowin website maybe it's that ?

I have an error after downloading the bitstream but I read on [this issue](https://github.com/trabucayre/openFPGALoader/issues/14) that is a known bug.

**Comment by pepijndevos** [comment]
Can you share the output of the unpack and show steps? Show can be told to output a PNG or SVG rather than show a window. The key thing to look for is if the inputs are fully connected to the outputs.

If there is nothing to render, this is a very bad sign. Remove the purge argument and try again. This will produce a HUGE graph. You can look at the source code and search for the IOB locations. As mentioned, I have a hunch that your IOB did not get created correctly.

You can also pass a selector to show, to only show the IOB, or you can of course just look at unpack.v and search around.

**Comment by Martoni** [comment]
Solved by trabucayre [PR](https://github.com/pepijndevos/apicula/pull/10) !

**Comment by pepijndevos** [comment]
Cool, so you have a working blinky! Yay!

**Comment by Martoni** [comment]
https://www.youtube.com/watch?v=yc2yBYlCCI4&feature=youtu.be

\o/
